import { create } from 'zustand';
const useStore = create((set, get) => ({
  user: null,
  isPro: false,
  impactScore: 742,
  bestHour: 22,
  streak: 7,
  xp: 1240,
  level: 5,
  goals: [],
  activeGoal: null,
  missions: [],
  activeMission: null,
  missionTimer: 1200,
  proofs: [],
  proofCount: 0,
  voiceActive: false,
  lumaReply: '',
  coachStyle: 'friend',
  setUser: (user) => set({ user }),
  setIsPro: (isPro) => set({ isPro }),
  setActiveMission: (mission) => set({ activeMission: mission }),
  setMissionTimer: (time) => set({ missionTimer: time }),
  addProof: (proof) => set((state) => ({ proofs: [...state.proofs, proof], proofCount: state.proofCount + 1 })),
  setLumaReply: (reply) => set({ lumaReply: reply }),
  setVoiceActive: (active) => set({ voiceActive: active }),
  addGoal: (goal) => set((state) => ({ goals: [...state.goals, { id: Date.now(), ...goal, status: 'active' }] })),
  addMission: (mission) => set((state) => ({ missions: [...state.missions, { id: Date.now(), ...mission, status: 'pending' }] })),
  completeMission: () => set((state) => ({
    missions: state.missions.map(m => m.id === state.activeMission?.id ? { ...m, status: 'completed' } : m),
    xp: state.xp + 100,
    impactScore: state.impactScore + 50,
  })),
}));
export default useStore;